exampleSite/config.toml
layouts/_default/taxonomy.html
layouts/partials/post/copyright.html
layouts/post/single.html
layouts/post/summary.html

Added the functionality to customize the date format, looks good?

feat: provide the facility to customize date format

---

i18n/fr.yaml

Hi,
Great theme, thanks! I just added ai18n for French.
Damien G.

add a i18n yaml file for French

---

archetypes/default.md
exampleSite/content/post/hidden-post.md
layouts/index.html

Use `hidden: true` to hide a post on the index page.

feat: add hiddenFromHomePage param

---

i18n/es.yaml

Add es i18n

---

exampleSite/config.toml

preserve taxonomy

---

src/css/_variables.scss

style: change code-font-family

---

layouts/partials/scripts.html

https://github.com/gohugoio/hugo/commit/1823c053c8900cb6ee53b8e5c02939c7398e34dd

feat(scripts): disable google analytics on localhost

---

exampleSite/config.toml
layouts/partials/post/copyright.html

preview:
ref: https://gohugo.io/variables/git/

feat(lastmod): use git commit to generate lastmod info

---

src/css/_partial/_post/_content.scss
src/css/_variables.scss

Fix code font size and extra mathjax scoll bar

---

layouts/partials/comments.html

https://github.com/olOwOlo/hugo-theme-even/issues/121

Added sid for Changyan comments

---

exampleSite/config.toml
layouts/partials/comments.html

Second time doing this. 😢
Reference:
https://www.smslit.top/2018/07/08/hugo-valine/
#95

Valine Support

---

layouts/partials/comments.html

Fix gitment's error: "[object ProgressEvent]". The solution is from this [link](https://github.com/imsun/gitment/issues/170#issuecomment-453845148).

fix gitment object progressEvent error

---

assets/js/even.js

fix(js): add wrapper for all tables

---

.gitignore

One more finding of old unused entries.
Thanks a lot for this great theme,
Florian La Roche

remove .gitignore entries not needed anymore

---

layouts/partials/head.html
layouts/partials/scripts.html

This used to be relative links and I think should be fine to stay relative links.
Thanks a lot for this great theme,
Florian La Roche

use relative links

---

i18n/jp.yaml

Adding Japanese language
(perhaps need a different Japanese font in future)

Add jp i18n

---

layouts/partials/scripts.html

Patch taken from https://github.com/sdvcrx/hugo-theme-even/commit/60633a072ea1cf3b0cd268b986d27bc5dd6ca5d1

minify main.js

---

i18n/de.yaml

add German translation

---

assets/sass/_iconfont.scss
assets/sass/_variables.scss

根据 https://web.dev/font-display/#how-to-avoid-showing-invisible-text

加上 "font-display: swap" ，优化 css 性能。

---

i18n/zh-TW.yaml

Add Taiwanese Traditional Chinese translation

feat(i18n): add Traditional Chinese translation

---

i18n/ru.yaml

i18n(ru): Add russian translation
